-- Classifica sexo em saude_mental_inscritos pelo primeiro nome.
-- Só preenche onde sexo ainda está vazio. É seguro executar de novo.
-- Execute no SQL Editor do Supabase.

CREATE OR REPLACE FUNCTION public.classificar_sexo_por_primeiro_nome(p_nome TEXT)
RETURNS TEXT
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
  v TEXT;
  fem TEXT[] := ARRAY[
    'MARIA','ANA','JOANA','FRANCISCA','ANTONIA','ADRIANA','JULIANA','MARCIA','FERNANDA',
    'PATRICIA','ALINE','SANDRA','CAMILA','AMANDA','BRUNA','JESSICA','LETICIA','JULIA',
    'BEATRIZ','LARISSA','GABRIELA','RAFAELA','VANESSA','CAROLINA','NATALIA','RENATA',
    'LUCIANA','SIMONE','CRISTIANE','CLAUDIA','DANIELA','TATIANE','PRISCILA','ROBERTA',
    'ANDREIA','ANDREA','SONIA','LUCIA','HELENA','ALICE','LAURA','SOFIA','SOPHIA',
    'ISABELA','ISABELLA','MANUELA','VALENTINA','LIVIA','LORENA','CECILIA','CATARINA',
    'MARIANA','BARBARA','RAQUEL','RUTH','ESTER','ESTHER','INGRID','ELIANE','ROSANGELA',
    'APARECIDA','CONCEICAO','FATIMA','REGINA','VERA','NEUSA','NEUZA','TEREZINHA','TERESA',
    'TERESINHA','IRACEMA','CLEIDE','IVONE','IVONETE','SOLANGE','ROSELI','EDNA','DIRCE',
    'BENEDITA','SEBASTIANA','LUANA','NATALI','NATHALIA','NATHALI','KARINA','CARINA',
    'SABRINA','MONICA','MONIQUE','MICHELE','MICHELLE','ELAINE','ELIANE','SUELI','SUELY',
    'LUCIENE','LUCIANA','ROSANA','ROSANGELA','ROSE','ROSIMEIRE','CLEONICE','IVANETE',
    'IVANILDE','MARLENE','MARILENE','MARILDA','MARILENE','MADALENA','MAGDA','MARGARIDA',
    'MARTA','MARTHA','MATILDE','MIRIAM','MIRIAN','NOEMIA','ODETE','OLGA','PALMIRA',
    'PEROLA','PILAR','RITA','ROSA','ROSALIA','SALETE','SELMA','SILVANA','SIRLENE',
    'SONIA','SUZANA','SUZANE','TANIA','TELMA','VALDIRENE','VALERIA','VANIA','VERA',
    'VILMA','VITORIA','YASMIN','YASMIM','HELOISA','ELOISA','LUIZA','LUIZA','ISIS',
    'JAQUELINE','JACQUELINE','JOSIANE','JOSIANE','KATIA','CATIA','KEILA','KELLY',
    'LARA','LIA','LIDIA','LILIAN','LILIANE','LINDA','LINDINALVA','LUCI','LURDES',
    'LOURDES','MADALENA','NAIR','NILZA','NILCE','NUBIA','ODETE','ONEIDE','PEDRINA',
    'QUITERIA','RAIMUNDA','ROSALINA','ROSANGELA','ROSEANE','ROSILENE','SANDRA',
    'SHEILA','SHEYLA','SHIRLEY','SILVIA','SILVIA','TAIS','THAIS','THAISSA','THAISSA',
    'VIVIAN','VIVIANE','WANESSA','ZILDA','ZULEICA','ZULEIKA','DAIANE','DAYANE',
    'TATIANA','CRISTINA','FABIANA','FABIANE','FLAVIA','GABRIELLE','GISELE','GISELLE',
    'GRAZIELA','GRAZIELLE','IANE','IARA','ILDA','ILZA','INEZ','INES','IRIS','ISA',
    'ISABEL','ISADORA','IVANA','JANA','JANAINA','JANETE','JANE','JANETE','JOICE',
    'JOSEFA','JOSELIA','JUCELIA','JUCIARA','JUCELINA','JULIANA','JUREMA','KAREN',
    'KAROLINE','KAROLINA','KATIA','LAIS','LAISA','LARISSA','LEILA','LENIR','LENIRA',
    'LEONOR','LEONORA','LIGIA','LILIA','LUCIA','LUCILENE','LUCIMAR','LUCINEIA',
    'LUCINEIDE','LUDIMILA','LUISA','LUIZA','MABEL','MAIARA','MAYARA','MARCELA',
    'MARCIA','MARCILEIA','MARIA','MARILENE','MARILU','MARINA','MARISE','MARLENE',
    'MEIRE','MEYRE','MILENA','MIRTES','NADIA','NADJA','NAIARA','NAYARA','NARA',
    'NATALIA','NEIDE','NERI','NICE','NILDENE','NOEMI','NORMA','ODELIA','OLIVIA',
    'ORLANDINA','PAMELA','PAULA','PAULINA','PENHA','POLIANA','PRISCYLA','RAFAELA',
    'REBECA','REBECCA','REGIANE','REJANE','RENATA','RITA','ROBERTA','ROMILDA',
    'ROSANA','ROSANGELA','ROSARIA','ROSARIO','ROSEMARY','SABRINA','SAMANTA','SAMANTHA',
    'SARA','SARAH','SELMA','SERGIA','SEVERINA','SIDNEIA','SILMARA','SIMONE','SIRLEI',
    'SONIA','STELA','STELLA','SUSANA','SUZANA','TAMIRES','TAMIRIS','TATIANA','TELMA',
    'TEREZA','VALDENICE','VALERIA','VANESSA','VANILDA','VERONICA','VITORIA','YARA'
  ];
  masc TEXT[] := ARRAY[
    'JOAO','JOSE','ANTONIO','FRANCISCO','PAULO','PEDRO','LUCAS','LUIS','LUIZ','CARLOS',
    'MARCOS','MARCELO','RAFAEL','GABRIEL','FELIPE','FILIPE','BRUNO','RODRIGO','ANDERSON',
    'ANDRE','DANIEL','EDUARDO','RICARDO','ROBERTO','ROBSON','FABIO','FERNANDO','LEANDRO',
    'ALEXANDRE','DIEGO','DIOGO','THIAGO','TIAGO','GUILHERME','GUSTAVO','HENRIQUE',
    'VINICIUS','MATEUS','MATHEUS','CAIO','KAIO','IGOR','IAGO','YAGO','MIGUEL','ARTHUR',
    'ARTUR','DAVI','DAVID','HEITOR','BERNARDO','LORENZO','ENZO','GAEL','RUAN','RYAN',
    'NICOLAS','OTAVIO','SERGIO','CLAUDIO','SEBASTIAO','MANOEL','MANUEL','JORGE','EDSON',
    'EDILSON','ADEMIR','JAIR','JAIME','JAIRO','WILSON','NILSON','NELSON','MARCIO','CESAR',
    'CEZAR','WAGNER','VAGNER','ROGERIO','RONALDO','ROMULO','SAMUEL','SAULO','ELIAS',
    'JONAS','JONATAS','TOBIAS','ISAIAS','MOISES','ADILSON','ADRIANO','ALAN','ALLAN',
    'ALEX','ALISSON','ALYSSON','ANGELO','AUGUSTO','BENEDITO','CELSO','CICERO','CLEBER',
    'CLEITON','CRISTIANO','DOUGLAS','EDIVALDO','ELTON','EMERSON','EVANDRO','EVERTON',
    'EZEQUIEL','FABIANO','FLAVIO','GILBERTO','GILMAR','GILSON','HUGO','IVAN','IVO',
    'JEFERSON','JEFFERSON','JOAQUIM','JOEL','JONATHAN','JULIO','JUNIOR','KAUA','KAUAN',
    'KLEBER','LEONARDO','LEVI','LUAN','LUCIANO','MAICON','MARCIO','MARLON','MAURO',
    'MURILO','NATAN','NATHAN','NILTON','OSVALDO','OSWALDO','RAIMUNDO','RENAN','RENATO',
    'RODOLFO','RUBENS','SALVADOR','SANDRO','SILVIO','VALMIR','VANDERLEI','VICENTE',
    'VICTOR','VITOR','WALTER','WELLINGTON','WESLEY','WILLIAN','WILLIAM','YURI',
    'ABRAAO','ADAO','ADRIEL','AILTON','AIRTON','ALBERTO','ALCEU','ALCIDES','ALEXANDRO',
    'ALFREDO','AMARO','ANSELMO','ARLINDO','ARMANDO','ARNALDO','AUGUSTO','AURELIO',
    'BENICIO','BRENO','CAIQUE','CALEB','CARLOS','CELIO','CICERO','CLAUDEMIR','CLAUDINEI',
    'CLEBERSON','CRISTOVAO','DAMIAO','DANILO','DARLAN','DEIVID','DENIS','DENNIS',
    'DOMINGOS','EDER','EDERSON','EDILSON','EDMILSON','EDNALDO','EDUARDO','ELIEL',
    'ELIEZER','ELISEU','EMANUEL','EMILIO','ERALDO','ERICK','ERIK','ERIVALDO','EVERALDO',
    'EXPEDITO','FABRICIO','FLAVIO','FRANCISCO','GENIVALDO','GERALDO','GERSON','GILVAN',
    'HELDER','HELIO','HERBERT','HERMES','HILTON','IRAN','ISAAC','ISAQUE','ITALO',
    'ITAMAR','IVONALDO','JACKSON','JEAN','JEOVA','JEREMIAS','JOAB','JOAO','JOAQUIM',
    'JOSIAS','JOSUE','JUVENAL','LAERCIO','LAERTE','LEANDRO','LINDOMAR','LUCIO','LUCAS',
    'MAGNO','MAICON','MARCELINO','MARCILIO','MARIO','MAURICIO','MAURILIO','MAX',
    'MAXWELL','MESSIAS','MICHEL','MILTON','NATANAEL','NEEMIAS','NICOLAU','NILTON',
    'NORBERTO','ODAIR','ORLANDO','OSMAR','OZIAS','PATRICK','PATRICIO','PAULO','PEDRO',
    'RAFAEL','RAIMUNDO','REGINALDO','REINALDO','RENATO','RIVALDO','ROBERVAL','ROBSON',
    'ROGER','ROMARIO','RONEI','RONALDO','RUBEM','SAMUEL','SAULO','SERGIO','SEVERINO',
    'SIDNEI','SILAS','SILVIO','TALES','THALES','VALDECIR','VALDEMIR','VALDIR','VANDER',
    'VANDERLEI','VILMAR','VINICIUS','VITOR','WAGNER','WALDIR','WASHINGTON','WEDSON',
    'WEVERTON','WILLIAN','WILSON','XAVIER','ZACARIAS','ANANIAS','MATIAS','BARTOLOMEU'
  ];
  masc_termina_a TEXT[] := ARRAY[
    'ELIAS','JONAS','JONATAS','TOBIAS','ISAIAS','MESSIAS','ZACARIAS','ANANIAS','JOSIAS',
    'JEREMIAS','NEEMIAS','MATIAS','AZARIAS','OBADIAS','ESDRAS','LUCAS','NICOLAS'
  ];
BEGIN
  IF p_nome IS NULL OR btrim(p_nome) = '' THEN
    RETURN NULL;
  END IF;

  v := upper(btrim(split_part(replace(replace(p_nome, '-', ' '), '''', ' '), ' ', 1)));
  v := translate(v, 'ÁÀÂÃÄÉÈÊËÍÌÎÏÓÒÔÕÖÚÙÛÜÇÑÝ', 'AAAAAEEEEIIIIOOOOOUUUUCNY');
  v := regexp_replace(v, '[^A-Z]', '', 'g');

  IF v = '' OR v = ANY (ARRAY['DE','DA','DO','DAS','DOS','E']) THEN
    RETURN NULL;
  END IF;

  IF v = ANY (fem) THEN
    RETURN 'feminino';
  END IF;
  IF v = ANY (masc) OR v = ANY (masc_termina_a) THEN
    RETURN 'masculino';
  END IF;

  IF right(v, 1) = 'A' AND NOT (v = ANY (masc_termina_a)) THEN
    RETURN 'feminino';
  END IF;
  IF right(v, 1) = 'O' THEN
    RETURN 'masculino';
  END IF;
  IF v ~ '(INE|ANE|ETE|IDE|ISA|INA|ELA)$' THEN
    RETURN 'feminino';
  END IF;
  IF v ~ '(SON|TON|EL|ER|IM|OM|EU|AU|US|OS|EZ)$' THEN
    RETURN 'masculino';
  END IF;

  RETURN NULL;
END;
$$;

UPDATE public.saude_mental_inscritos
SET sexo = public.classificar_sexo_por_primeiro_nome(nome_completo),
    updated_at = now()
WHERE deleted_at IS NULL
  AND sexo IS NULL
  AND public.classificar_sexo_por_primeiro_nome(nome_completo) IS NOT NULL;

SELECT sexo, count(*) AS qtd
FROM public.saude_mental_inscritos
WHERE deleted_at IS NULL
GROUP BY sexo
ORDER BY qtd DESC;
