/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VivenciasRouteImport } from './routes/vivencias'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AcolhimentoRouteImport } from './routes/acolhimento'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfissionaisRouteImport } from './routes/_authenticated/profissionais'
import { Route as AuthenticatedEscolasRouteImport } from './routes/_authenticated/escolas'
import { Route as AuthenticatedDemandasRouteImport } from './routes/_authenticated/demandas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAprovacoesRouteImport } from './routes/_authenticated/aprovacoes'
import { Route as AuthenticatedAguardandoAprovacaoRouteImport } from './routes/_authenticated/aguardando-aprovacao'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedModuloVivenciasRouteRouteImport } from './routes/_authenticated/modulo-vivencias/route'
import { Route as AuthenticatedConfiguracoesRouteRouteImport } from './routes/_authenticated/configuracoes/route'
import { Route as AuthenticatedModuloVivenciasIndexRouteImport } from './routes/_authenticated/modulo-vivencias/index'
import { Route as AuthenticatedDemandasIndexRouteImport } from './routes/_authenticated/demandas.index'
import { Route as AuthenticatedModuloVivenciasDemandasRouteImport } from './routes/_authenticated/modulo-vivencias/demandas'
import { Route as AuthenticatedModuloVivenciasDashboardRouteImport } from './routes/_authenticated/modulo-vivencias/dashboard'
import { Route as AuthenticatedModuloVivenciasAgendaRouteImport } from './routes/_authenticated/modulo-vivencias/agenda'
import { Route as AuthenticatedDemandasIdRouteImport } from './routes/_authenticated/demandas.$id'
import { Route as AuthenticatedConfiguracoesUsuariosRouteImport } from './routes/_authenticated/configuracoes/usuarios'
import { Route as AuthenticatedModuloVivenciasDemandasIndexRouteImport } from './routes/_authenticated/modulo-vivencias/demandas.index'
import { Route as AuthenticatedModuloVivenciasDemandasIdRouteImport } from './routes/_authenticated/modulo-vivencias/demandas.$id'

const VivenciasRoute = VivenciasRouteImport.update({
  id: '/vivencias',
  path: '/vivencias',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcolhimentoRoute = AcolhimentoRouteImport.update({
  id: '/acolhimento',
  path: '/acolhimento',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfissionaisRoute =
  AuthenticatedProfissionaisRouteImport.update({
    id: '/profissionais',
    path: '/profissionais',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEscolasRoute = AuthenticatedEscolasRouteImport.update({
  id: '/escolas',
  path: '/escolas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDemandasRoute = AuthenticatedDemandasRouteImport.update({
  id: '/demandas',
  path: '/demandas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAprovacoesRoute = AuthenticatedAprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAguardandoAprovacaoRoute =
  AuthenticatedAguardandoAprovacaoRouteImport.update({
    id: '/aguardando-aprovacao',
    path: '/aguardando-aprovacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModuloVivenciasRouteRoute =
  AuthenticatedModuloVivenciasRouteRouteImport.update({
    id: '/modulo-vivencias',
    path: '/modulo-vivencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesRouteRoute =
  AuthenticatedConfiguracoesRouteRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModuloVivenciasIndexRoute =
  AuthenticatedModuloVivenciasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedModuloVivenciasRouteRoute,
  } as any)
const AuthenticatedDemandasIndexRoute =
  AuthenticatedDemandasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDemandasRoute,
  } as any)
const AuthenticatedModuloVivenciasDemandasRoute =
  AuthenticatedModuloVivenciasDemandasRouteImport.update({
    id: '/demandas',
    path: '/demandas',
    getParentRoute: () => AuthenticatedModuloVivenciasRouteRoute,
  } as any)
const AuthenticatedModuloVivenciasDashboardRoute =
  AuthenticatedModuloVivenciasDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedModuloVivenciasRouteRoute,
  } as any)
const AuthenticatedModuloVivenciasAgendaRoute =
  AuthenticatedModuloVivenciasAgendaRouteImport.update({
    id: '/agenda',
    path: '/agenda',
    getParentRoute: () => AuthenticatedModuloVivenciasRouteRoute,
  } as any)
const AuthenticatedDemandasIdRoute = AuthenticatedDemandasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedDemandasRoute,
} as any)
const AuthenticatedConfiguracoesUsuariosRoute =
  AuthenticatedConfiguracoesUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedConfiguracoesRouteRoute,
  } as any)
const AuthenticatedModuloVivenciasDemandasIndexRoute =
  AuthenticatedModuloVivenciasDemandasIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedModuloVivenciasDemandasRoute,
  } as any)
const AuthenticatedModuloVivenciasDemandasIdRoute =
  AuthenticatedModuloVivenciasDemandasIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedModuloVivenciasDemandasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acolhimento': typeof AcolhimentoRoute
  '/auth': typeof AuthRoute
  '/vivencias': typeof VivenciasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRouteRouteWithChildren
  '/modulo-vivencias': typeof AuthenticatedModuloVivenciasRouteRouteWithChildren
  '/agenda': typeof AuthenticatedAgendaRoute
  '/aguardando-aprovacao': typeof AuthenticatedAguardandoAprovacaoRoute
  '/aprovacoes': typeof AuthenticatedAprovacoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/demandas': typeof AuthenticatedDemandasRouteWithChildren
  '/escolas': typeof AuthenticatedEscolasRoute
  '/profissionais': typeof AuthenticatedProfissionaisRoute
  '/configuracoes/usuarios': typeof AuthenticatedConfiguracoesUsuariosRoute
  '/demandas/$id': typeof AuthenticatedDemandasIdRoute
  '/modulo-vivencias/agenda': typeof AuthenticatedModuloVivenciasAgendaRoute
  '/modulo-vivencias/dashboard': typeof AuthenticatedModuloVivenciasDashboardRoute
  '/modulo-vivencias/demandas': typeof AuthenticatedModuloVivenciasDemandasRouteWithChildren
  '/demandas/': typeof AuthenticatedDemandasIndexRoute
  '/modulo-vivencias/': typeof AuthenticatedModuloVivenciasIndexRoute
  '/modulo-vivencias/demandas/$id': typeof AuthenticatedModuloVivenciasDemandasIdRoute
  '/modulo-vivencias/demandas/': typeof AuthenticatedModuloVivenciasDemandasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acolhimento': typeof AcolhimentoRoute
  '/auth': typeof AuthRoute
  '/vivencias': typeof VivenciasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRouteRouteWithChildren
  '/agenda': typeof AuthenticatedAgendaRoute
  '/aguardando-aprovacao': typeof AuthenticatedAguardandoAprovacaoRoute
  '/aprovacoes': typeof AuthenticatedAprovacoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/escolas': typeof AuthenticatedEscolasRoute
  '/profissionais': typeof AuthenticatedProfissionaisRoute
  '/configuracoes/usuarios': typeof AuthenticatedConfiguracoesUsuariosRoute
  '/demandas/$id': typeof AuthenticatedDemandasIdRoute
  '/modulo-vivencias/agenda': typeof AuthenticatedModuloVivenciasAgendaRoute
  '/modulo-vivencias/dashboard': typeof AuthenticatedModuloVivenciasDashboardRoute
  '/demandas': typeof AuthenticatedDemandasIndexRoute
  '/modulo-vivencias': typeof AuthenticatedModuloVivenciasIndexRoute
  '/modulo-vivencias/demandas/$id': typeof AuthenticatedModuloVivenciasDemandasIdRoute
  '/modulo-vivencias/demandas': typeof AuthenticatedModuloVivenciasDemandasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/acolhimento': typeof AcolhimentoRoute
  '/auth': typeof AuthRoute
  '/vivencias': typeof VivenciasRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRouteRouteWithChildren
  '/_authenticated/modulo-vivencias': typeof AuthenticatedModuloVivenciasRouteRouteWithChildren
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/aguardando-aprovacao': typeof AuthenticatedAguardandoAprovacaoRoute
  '/_authenticated/aprovacoes': typeof AuthenticatedAprovacoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/demandas': typeof AuthenticatedDemandasRouteWithChildren
  '/_authenticated/escolas': typeof AuthenticatedEscolasRoute
  '/_authenticated/profissionais': typeof AuthenticatedProfissionaisRoute
  '/_authenticated/configuracoes/usuarios': typeof AuthenticatedConfiguracoesUsuariosRoute
  '/_authenticated/demandas/$id': typeof AuthenticatedDemandasIdRoute
  '/_authenticated/modulo-vivencias/agenda': typeof AuthenticatedModuloVivenciasAgendaRoute
  '/_authenticated/modulo-vivencias/dashboard': typeof AuthenticatedModuloVivenciasDashboardRoute
  '/_authenticated/modulo-vivencias/demandas': typeof AuthenticatedModuloVivenciasDemandasRouteWithChildren
  '/_authenticated/demandas/': typeof AuthenticatedDemandasIndexRoute
  '/_authenticated/modulo-vivencias/': typeof AuthenticatedModuloVivenciasIndexRoute
  '/_authenticated/modulo-vivencias/demandas/$id': typeof AuthenticatedModuloVivenciasDemandasIdRoute
  '/_authenticated/modulo-vivencias/demandas/': typeof AuthenticatedModuloVivenciasDemandasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acolhimento'
    | '/auth'
    | '/vivencias'
    | '/configuracoes'
    | '/modulo-vivencias'
    | '/agenda'
    | '/aguardando-aprovacao'
    | '/aprovacoes'
    | '/dashboard'
    | '/demandas'
    | '/escolas'
    | '/profissionais'
    | '/configuracoes/usuarios'
    | '/demandas/$id'
    | '/modulo-vivencias/agenda'
    | '/modulo-vivencias/dashboard'
    | '/modulo-vivencias/demandas'
    | '/demandas/'
    | '/modulo-vivencias/'
    | '/modulo-vivencias/demandas/$id'
    | '/modulo-vivencias/demandas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acolhimento'
    | '/auth'
    | '/vivencias'
    | '/configuracoes'
    | '/agenda'
    | '/aguardando-aprovacao'
    | '/aprovacoes'
    | '/dashboard'
    | '/escolas'
    | '/profissionais'
    | '/configuracoes/usuarios'
    | '/demandas/$id'
    | '/modulo-vivencias/agenda'
    | '/modulo-vivencias/dashboard'
    | '/demandas'
    | '/modulo-vivencias'
    | '/modulo-vivencias/demandas/$id'
    | '/modulo-vivencias/demandas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/acolhimento'
    | '/auth'
    | '/vivencias'
    | '/_authenticated/configuracoes'
    | '/_authenticated/modulo-vivencias'
    | '/_authenticated/agenda'
    | '/_authenticated/aguardando-aprovacao'
    | '/_authenticated/aprovacoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/demandas'
    | '/_authenticated/escolas'
    | '/_authenticated/profissionais'
    | '/_authenticated/configuracoes/usuarios'
    | '/_authenticated/demandas/$id'
    | '/_authenticated/modulo-vivencias/agenda'
    | '/_authenticated/modulo-vivencias/dashboard'
    | '/_authenticated/modulo-vivencias/demandas'
    | '/_authenticated/demandas/'
    | '/_authenticated/modulo-vivencias/'
    | '/_authenticated/modulo-vivencias/demandas/$id'
    | '/_authenticated/modulo-vivencias/demandas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcolhimentoRoute: typeof AcolhimentoRoute
  AuthRoute: typeof AuthRoute
  VivenciasRoute: typeof VivenciasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vivencias': {
      id: '/vivencias'
      path: '/vivencias'
      fullPath: '/vivencias'
      preLoaderRoute: typeof VivenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acolhimento': {
      id: '/acolhimento'
      path: '/acolhimento'
      fullPath: '/acolhimento'
      preLoaderRoute: typeof AcolhimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profissionais': {
      id: '/_authenticated/profissionais'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof AuthenticatedProfissionaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escolas': {
      id: '/_authenticated/escolas'
      path: '/escolas'
      fullPath: '/escolas'
      preLoaderRoute: typeof AuthenticatedEscolasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demandas': {
      id: '/_authenticated/demandas'
      path: '/demandas'
      fullPath: '/demandas'
      preLoaderRoute: typeof AuthenticatedDemandasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aprovacoes': {
      id: '/_authenticated/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/aprovacoes'
      preLoaderRoute: typeof AuthenticatedAprovacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aguardando-aprovacao': {
      id: '/_authenticated/aguardando-aprovacao'
      path: '/aguardando-aprovacao'
      fullPath: '/aguardando-aprovacao'
      preLoaderRoute: typeof AuthenticatedAguardandoAprovacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modulo-vivencias': {
      id: '/_authenticated/modulo-vivencias'
      path: '/modulo-vivencias'
      fullPath: '/modulo-vivencias'
      preLoaderRoute: typeof AuthenticatedModuloVivenciasRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/modulo-vivencias/': {
      id: '/_authenticated/modulo-vivencias/'
      path: '/'
      fullPath: '/modulo-vivencias/'
      preLoaderRoute: typeof AuthenticatedModuloVivenciasIndexRouteImport
      parentRoute: typeof AuthenticatedModuloVivenciasRouteRoute
    }
    '/_authenticated/demandas/': {
      id: '/_authenticated/demandas/'
      path: '/'
      fullPath: '/demandas/'
      preLoaderRoute: typeof AuthenticatedDemandasIndexRouteImport
      parentRoute: typeof AuthenticatedDemandasRoute
    }
    '/_authenticated/modulo-vivencias/demandas': {
      id: '/_authenticated/modulo-vivencias/demandas'
      path: '/demandas'
      fullPath: '/modulo-vivencias/demandas'
      preLoaderRoute: typeof AuthenticatedModuloVivenciasDemandasRouteImport
      parentRoute: typeof AuthenticatedModuloVivenciasRouteRoute
    }
    '/_authenticated/modulo-vivencias/dashboard': {
      id: '/_authenticated/modulo-vivencias/dashboard'
      path: '/dashboard'
      fullPath: '/modulo-vivencias/dashboard'
      preLoaderRoute: typeof AuthenticatedModuloVivenciasDashboardRouteImport
      parentRoute: typeof AuthenticatedModuloVivenciasRouteRoute
    }
    '/_authenticated/modulo-vivencias/agenda': {
      id: '/_authenticated/modulo-vivencias/agenda'
      path: '/agenda'
      fullPath: '/modulo-vivencias/agenda'
      preLoaderRoute: typeof AuthenticatedModuloVivenciasAgendaRouteImport
      parentRoute: typeof AuthenticatedModuloVivenciasRouteRoute
    }
    '/_authenticated/demandas/$id': {
      id: '/_authenticated/demandas/$id'
      path: '/$id'
      fullPath: '/demandas/$id'
      preLoaderRoute: typeof AuthenticatedDemandasIdRouteImport
      parentRoute: typeof AuthenticatedDemandasRoute
    }
    '/_authenticated/configuracoes/usuarios': {
      id: '/_authenticated/configuracoes/usuarios'
      path: '/usuarios'
      fullPath: '/configuracoes/usuarios'
      preLoaderRoute: typeof AuthenticatedConfiguracoesUsuariosRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRouteRoute
    }
    '/_authenticated/modulo-vivencias/demandas/': {
      id: '/_authenticated/modulo-vivencias/demandas/'
      path: '/'
      fullPath: '/modulo-vivencias/demandas/'
      preLoaderRoute: typeof AuthenticatedModuloVivenciasDemandasIndexRouteImport
      parentRoute: typeof AuthenticatedModuloVivenciasDemandasRoute
    }
    '/_authenticated/modulo-vivencias/demandas/$id': {
      id: '/_authenticated/modulo-vivencias/demandas/$id'
      path: '/$id'
      fullPath: '/modulo-vivencias/demandas/$id'
      preLoaderRoute: typeof AuthenticatedModuloVivenciasDemandasIdRouteImport
      parentRoute: typeof AuthenticatedModuloVivenciasDemandasRoute
    }
  }
}

interface AuthenticatedConfiguracoesRouteRouteChildren {
  AuthenticatedConfiguracoesUsuariosRoute: typeof AuthenticatedConfiguracoesUsuariosRoute
}

const AuthenticatedConfiguracoesRouteRouteChildren: AuthenticatedConfiguracoesRouteRouteChildren =
  {
    AuthenticatedConfiguracoesUsuariosRoute:
      AuthenticatedConfiguracoesUsuariosRoute,
  }

const AuthenticatedConfiguracoesRouteRouteWithChildren =
  AuthenticatedConfiguracoesRouteRoute._addFileChildren(
    AuthenticatedConfiguracoesRouteRouteChildren,
  )

interface AuthenticatedModuloVivenciasDemandasRouteChildren {
  AuthenticatedModuloVivenciasDemandasIdRoute: typeof AuthenticatedModuloVivenciasDemandasIdRoute
  AuthenticatedModuloVivenciasDemandasIndexRoute: typeof AuthenticatedModuloVivenciasDemandasIndexRoute
}

const AuthenticatedModuloVivenciasDemandasRouteChildren: AuthenticatedModuloVivenciasDemandasRouteChildren =
  {
    AuthenticatedModuloVivenciasDemandasIdRoute:
      AuthenticatedModuloVivenciasDemandasIdRoute,
    AuthenticatedModuloVivenciasDemandasIndexRoute:
      AuthenticatedModuloVivenciasDemandasIndexRoute,
  }

const AuthenticatedModuloVivenciasDemandasRouteWithChildren =
  AuthenticatedModuloVivenciasDemandasRoute._addFileChildren(
    AuthenticatedModuloVivenciasDemandasRouteChildren,
  )

interface AuthenticatedModuloVivenciasRouteRouteChildren {
  AuthenticatedModuloVivenciasAgendaRoute: typeof AuthenticatedModuloVivenciasAgendaRoute
  AuthenticatedModuloVivenciasDashboardRoute: typeof AuthenticatedModuloVivenciasDashboardRoute
  AuthenticatedModuloVivenciasDemandasRoute: typeof AuthenticatedModuloVivenciasDemandasRouteWithChildren
  AuthenticatedModuloVivenciasIndexRoute: typeof AuthenticatedModuloVivenciasIndexRoute
}

const AuthenticatedModuloVivenciasRouteRouteChildren: AuthenticatedModuloVivenciasRouteRouteChildren =
  {
    AuthenticatedModuloVivenciasAgendaRoute:
      AuthenticatedModuloVivenciasAgendaRoute,
    AuthenticatedModuloVivenciasDashboardRoute:
      AuthenticatedModuloVivenciasDashboardRoute,
    AuthenticatedModuloVivenciasDemandasRoute:
      AuthenticatedModuloVivenciasDemandasRouteWithChildren,
    AuthenticatedModuloVivenciasIndexRoute:
      AuthenticatedModuloVivenciasIndexRoute,
  }

const AuthenticatedModuloVivenciasRouteRouteWithChildren =
  AuthenticatedModuloVivenciasRouteRoute._addFileChildren(
    AuthenticatedModuloVivenciasRouteRouteChildren,
  )

interface AuthenticatedDemandasRouteChildren {
  AuthenticatedDemandasIdRoute: typeof AuthenticatedDemandasIdRoute
  AuthenticatedDemandasIndexRoute: typeof AuthenticatedDemandasIndexRoute
}

const AuthenticatedDemandasRouteChildren: AuthenticatedDemandasRouteChildren = {
  AuthenticatedDemandasIdRoute: AuthenticatedDemandasIdRoute,
  AuthenticatedDemandasIndexRoute: AuthenticatedDemandasIndexRoute,
}

const AuthenticatedDemandasRouteWithChildren =
  AuthenticatedDemandasRoute._addFileChildren(
    AuthenticatedDemandasRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConfiguracoesRouteRoute: typeof AuthenticatedConfiguracoesRouteRouteWithChildren
  AuthenticatedModuloVivenciasRouteRoute: typeof AuthenticatedModuloVivenciasRouteRouteWithChildren
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedAguardandoAprovacaoRoute: typeof AuthenticatedAguardandoAprovacaoRoute
  AuthenticatedAprovacoesRoute: typeof AuthenticatedAprovacoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDemandasRoute: typeof AuthenticatedDemandasRouteWithChildren
  AuthenticatedEscolasRoute: typeof AuthenticatedEscolasRoute
  AuthenticatedProfissionaisRoute: typeof AuthenticatedProfissionaisRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConfiguracoesRouteRoute:
    AuthenticatedConfiguracoesRouteRouteWithChildren,
  AuthenticatedModuloVivenciasRouteRoute:
    AuthenticatedModuloVivenciasRouteRouteWithChildren,
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedAguardandoAprovacaoRoute: AuthenticatedAguardandoAprovacaoRoute,
  AuthenticatedAprovacoesRoute: AuthenticatedAprovacoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDemandasRoute: AuthenticatedDemandasRouteWithChildren,
  AuthenticatedEscolasRoute: AuthenticatedEscolasRoute,
  AuthenticatedProfissionaisRoute: AuthenticatedProfissionaisRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcolhimentoRoute: AcolhimentoRoute,
  AuthRoute: AuthRoute,
  VivenciasRoute: VivenciasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
