/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AcolhimentoRouteImport } from './routes/acolhimento'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDemandasRouteImport } from './routes/_authenticated/demandas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDemandasIdRouteImport } from './routes/_authenticated/demandas.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcolhimentoRoute = AcolhimentoRouteImport.update({
  id: '/acolhimento',
  path: '/acolhimento',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDemandasRoute = AuthenticatedDemandasRouteImport.update({
  id: '/demandas',
  path: '/demandas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDemandasIdRoute = AuthenticatedDemandasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedDemandasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acolhimento': typeof AcolhimentoRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/demandas': typeof AuthenticatedDemandasRouteWithChildren
  '/demandas/$id': typeof AuthenticatedDemandasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acolhimento': typeof AcolhimentoRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/demandas': typeof AuthenticatedDemandasRouteWithChildren
  '/demandas/$id': typeof AuthenticatedDemandasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/acolhimento': typeof AcolhimentoRoute
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/demandas': typeof AuthenticatedDemandasRouteWithChildren
  '/_authenticated/demandas/$id': typeof AuthenticatedDemandasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acolhimento'
    | '/auth'
    | '/dashboard'
    | '/demandas'
    | '/demandas/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acolhimento'
    | '/auth'
    | '/dashboard'
    | '/demandas'
    | '/demandas/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/acolhimento'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/demandas'
    | '/_authenticated/demandas/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcolhimentoRoute: typeof AcolhimentoRoute
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acolhimento': {
      id: '/acolhimento'
      path: '/acolhimento'
      fullPath: '/acolhimento'
      preLoaderRoute: typeof AcolhimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/demandas': {
      id: '/_authenticated/demandas'
      path: '/demandas'
      fullPath: '/demandas'
      preLoaderRoute: typeof AuthenticatedDemandasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demandas/$id': {
      id: '/_authenticated/demandas/$id'
      path: '/$id'
      fullPath: '/demandas/$id'
      preLoaderRoute: typeof AuthenticatedDemandasIdRouteImport
      parentRoute: typeof AuthenticatedDemandasRoute
    }
  }
}

interface AuthenticatedDemandasRouteChildren {
  AuthenticatedDemandasIdRoute: typeof AuthenticatedDemandasIdRoute
}

const AuthenticatedDemandasRouteChildren: AuthenticatedDemandasRouteChildren = {
  AuthenticatedDemandasIdRoute: AuthenticatedDemandasIdRoute,
}

const AuthenticatedDemandasRouteWithChildren =
  AuthenticatedDemandasRoute._addFileChildren(
    AuthenticatedDemandasRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDemandasRoute: typeof AuthenticatedDemandasRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDemandasRoute: AuthenticatedDemandasRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcolhimentoRoute: AcolhimentoRoute,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
